[arch]
packages = [
  "firefox",
  "google-chrome",
  "telegram-desktop",

  "yazi",
  "nemo",
  "file-roller",
  "nemo-fileroller",

  "blueman",

  "obsidian",

  "libreoffice-still",

  "obs-studio",
]
