[arch]
packages = [
  "base",
  "base-devel",
  "linux",
  "linux-firmware",
  "intel-ucode",
  "sof-firmware",
  "sudo",
  "grub",
  "os-prober",
  "efibootmgr",
  "fail2ban",
  "mkinitcpio",
  "nftables",
  "openssh",
  "wget",

  "paru",
  "paru-debug",
  "flatpak",

  "fish",
  "fisher",

  "downgrade"
]
