[arch]
packages = [
  # Utils
  "git",
  "lazygit",

  # Editors
  "nano",
  "vim",
  "neovim",
  "visual-studio-code-bin",

  # Python
  "uv",

  # C++
  "gcc",
  "gdb",
  # "codelldb",
  "lldb",
  "valgrind",
  "clang",
  "cmake",

  # Node js
  "mise",

  # Rust
  "rustup",
  "rust-analyzer"
]

[mise]
packages = [{ name = "node", options = { version = "lts" } }]

[npm]
packages = [
  "@openai/codex",
  "corepack",
  "npm",
]
