[arch]
packages = [
  # Utils
  "git",
  "git-lfs",
  "lazygit",

  # Editors
  "nano",
  "vim",
  "neovim",
  "visual-studio-code-bin",

  # Python
  "uv",

  # C++
  "gcc",
  "gdb",
  # "codelldb",
  "lldb",
  "valgrind",
  "clang",
  "cmake",

  # Node js
  "mise",
  "nodejs-lts-jod",
  "npm",

  # Rust
  "rustup",
  "rust-analyzer",
]

[npm]
packages = [
  "@openai/codex",
]
