[arch]
packages = [
  "chezmoi",
  "metapac",
  "usbutils",
  "wl-clipboard",
  "xdg-user-dirs",
  "xdg-utils",
  "zram-generator",
  "polkit-kde-agent",
  "appstream",
  "hwloc",
  "libblake3",
  "libfyaml",
]
