enabled_backends = ["arch", "mise", "npm", "yarn"]

hostname_groups_enabled = true

[arch]
package_manager = "paru"

[hostname_groups]
"declarch-pc" = [
    "base",
    "utils",
    "intel",
    "nvidia",
    "core-graphics",
    "fonts",
    "audio",
    "hypr",
    "apps",
    "cli",
    "development",
    "network",
    "printing",
]